{% set version = "0.5.1" %}

package:
  name: tomlkit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tomlkit/tomlkit-{{ version }}.tar.gz
  sha256: ccd5bc26d816e8be75c31c7c2da70c4f4b3131248a47ad1ffc82f48764d1883c

build:
  number: 1000
  script:
    # Somehow, when pyproject.toml is present, it requires poetry on Windows.
    # However, even with that dependency satisfied, we get:
    # "tomlkit cannot depend on itself"
    - del pyproject.toml  # [win]
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - typing >=3.6,<4.0  # [py<35]
    - enum34 >=1.1,<2.0  # [py27]
    - functools32 >=3.2.3,<4.0.0  # [py27]

test:
  imports:
    - tomlkit

about:
  home: https://github.com/sdispater/tomlkit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Style preserving TOML library

extra:
  recipe-maintainers:
    - ocefpaf
