{% set name = "tomlkit" %}
{% set version = "0.12.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tomlkit-{{ version }}.tar.gz
  sha256: eef34fba39834d4d6b73c9ba7f3e4d1c417a4e56f89a7e96e090dd0d24b8fb3c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python >=3.7                           # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - poetry-core >=1.0.0a9
    - python >=3.7
  run:
    - python >=3.7

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - tomlkit

about:
  home: https://github.com/sdispater/tomlkit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Style preserving TOML library

extra:
  recipe-maintainers:
    - ocefpaf
