appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: cQpppw2UxKrdHWEv95xsnJONwhnR8dV265wUX8WJI9pxjr8aNl2uoJj1tDd0q+ujDVpoBsaAWZswWL5AnbHzhUfJR111CdIZhfn4/ET2eUiaPlMKkl1mYZKMr27IUeq+tcFejfd4VQmOVbn1wyhOBQAF+SYPcDZ7IKklfoRYnOwQAAvZAVL0D6PzHKYPmzccu4PtYlqFLrvzVYdEuejawLARdVSR8SIiS6Xo87uzT7Hso7KniaJY08z91rU8xLy2QK7LbKK0f/V+P/tR7ruG60vAvQODssCqkczhcT7OgiDk2H9StGPN+a6CaVdrKOat2K1Ye1kj9ALJZMLfoeys/Vhkx5EhswBlBNczEyCLqz2Sf9/FSkz7W+ymBRKPMxP0xrtWumeq1kQOzQUcTYonwXHU2tDMGtsHjZRb3oIvuoGipgurBWU+W3FL7MYQzAvjnN6RiCWGU+sk04U5q/bd7zajrAZLa9YigMCWYHgRRZyMkWMEv5p/FB9IbeksgCRC3bMbFMlnuiWrhpN4mcRz/MRgHXoE/XPGZFtVrLsdKcw1SK38YK5Yx8JZex4qfMeTEMqe4JlKXA+kOc0Yo+g1NJfE6KPpzuD7JE8PZec9nUfjkL2Co+jozSSv5Uz20Y6gkB3xsUozrNGRP6vub5mIzvKyXMGCTXOZ2coUkLCPmmg=}
